import Head from "next/head";
import LandingText from "@/components/landingText";
import Hero from "@/components/hero";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <LandingText />
        <div className="maincol flex h-[540px] flex-col items-center justify-center gap-10 py-32 text-center md:text-start lg:flex-row lg:items-stretch lg:gap-0">
          <h1 className="flex w-full items-start justify-start text-5xl font-light">
            SEASIDE ELEGANCE: YOUR PRIVATE PARADISE AWAITS
          </h1>
          <h2 className="flex w-full items-end justify-end text-lg font-extralight">
            Nestled along the pristine coastline, our luxury villa offers an
            unparalleled lifestyle of opulence and tranquility. The moment you
            step foot onto the grounds, you&apos;ll be captivated by the breathtaking
            panoramic views of the boundless sea.
          </h2>
        </div>
        <Hero />
      </div>
    </>
  );
}
